export const clientTemplate = (): string =>
  `// This file is auto-generated by the EdgePod CLI.
// Feel free to amend this file to suit your needs.
export { EdgePodProvider, useStatus, $wsStatus } from "@edgepod/client";

import { useQuery as baseUseQuery, useMutation as baseUseMutation } from "@edgepod/client";
import type * as functions from "./functions";

type Router = {
  [K in keyof typeof functions]: {
    args: Parameters<(typeof functions)[K]> extends [any, infer P] ? P : undefined;
    returns: Awaited<ReturnType<(typeof functions)[K]>>;
  };
};

type UseQueryOptions<T> = {
  fallbackData?: T;
  onSuccess?: (data: T) => void;
  onError?: (error: Error) => void;
  suspense?: boolean;
  errorRetryCount?: number;
};

type UseMutationOptions<T> = {
  onSuccess?: (data: T) => void;
  onError?: (error: Error) => void;
};

export function useQuery<K extends keyof Router & string>(
  functionName: K,
  args?: Router[K]["args"] | null,
  options?: UseQueryOptions<Router[K]["returns"]>,
) {
  return baseUseQuery<Router[K]["returns"]>(
    functionName,
    args as Record<string, unknown> | null | undefined,
    options,
  );
}

export function useMutation<K extends keyof Router & string>(
  functionName: K,
  options?: UseMutationOptions<Router[K]["returns"]>,
) {
  return baseUseMutation<Router[K]["returns"], Router[K]["args"]>(functionName, options);
}
`;
