import fs from "node:fs/promises";
import { consola } from "consola";
import { functionsIndexTemplate } from "../templates/functions";
import { schemaTemplate } from "../templates/schema";
import { wranglerJsonTemplate } from "../templates/wrangler";
import { genTypesTemplate } from "../templates/types";
import { serverTemplate } from "../templates/server";
import type { DataLocationOptions } from "../templates/server";

export const createFiles = async (projectRoot: string, opts?: DataLocationOptions) => {
  const emptyMigrationsIndex = `// Auto-generated by EdgePod CLI — do not edit manually.
// Run \`edgepod build\` to regenerate after schema changes.

export default null;
`;

  const files = [
    ["edgepod/types.ts", genTypesTemplate()],
    ["edgepod/schema.ts", schemaTemplate()],
    ["edgepod/functions/index.ts", functionsIndexTemplate()],
    ["edgepod/.generated/server.ts", serverTemplate(opts)],
    ["edgepod/.generated/migrations/index.ts", emptyMigrationsIndex],
  ];

  const results = await Promise.all(
    files.map(async (file) => {
      const fullPath = `${projectRoot}/${file[0]}`;
      await fs.mkdir(fullPath.substring(0, fullPath.lastIndexOf("/")), { recursive: true });
      return fs
        .writeFile(fullPath, file[1] ?? "", { flag: "wx" })
        .then(() => true)
        .catch((e: NodeJS.ErrnoException) => {
          if (e.code === "EEXIST") return false;
          throw e;
        });
    })
  );

  const created = results.filter(Boolean).length;

  if (created === files.length) {
    consola.success("Created project files.");
  } else if (created === 0) {
    consola.warn("Project files already exist, skipping.");
  } else {
    consola.success(`Created ${created} project file(s).`);
    consola.warn(`${files.length - created} file(s) already existed, skipped.`);
  }
};

export const generateWranglerFromTemplate = async (projectRoot: string, apiKey: string) => {
  const wranglerJsonPath = `${projectRoot}/edgepod/wrangler.json`;
  await fs.mkdir(`${projectRoot}/edgepod`, { recursive: true });

  const created = await fs
    .writeFile(wranglerJsonPath, wranglerJsonTemplate(apiKey), { flag: "wx" })
    .then(() => true)
    .catch((e: NodeJS.ErrnoException) => {
      if (e.code === "EEXIST") return false;
      throw e;
    });

  if (created) {
    consola.success("Created edgepod/wrangler.json.");
  } else {
    consola.warn("edgepod/wrangler.json already exists, skipping.");
  }
};

export const writeEnvFile = async (projectRoot: string, apiKey: string) => {
  const envPath = `${projectRoot}/edgepod/.env`;

  const created = await fs
    .writeFile(envPath, `EDGEPOD_API_KEY=${apiKey}\n`, { flag: "wx" })
    .then(() => true)
    .catch((e: NodeJS.ErrnoException) => {
      if (e.code === "EEXIST") return false;
      throw e;
    });

  if (created) {
    consola.success("Created edgepod/.env with your API key.");
  } else {
    consola.warn("edgepod/.env already exists, skipping.");
  }
};

export const updateGitignore = async (projectRoot: string) => {
  const gitignorePath = `${projectRoot}/.gitignore`;
  const entries = ["edgepod/.env", "edgepod/.wrangler", "!edgepod/"];

  let existing = "";
  try {
    existing = await fs.readFile(gitignorePath, "utf-8");
  } catch {
    // file doesn't exist yet — we'll create it
  }

  const lines = existing.split("\n").map((l) => l.trim());
  const toAdd = entries.filter((e) => !lines.includes(e));

  if (toAdd.length === 0) return;

  const addition =
    (existing.endsWith("\n") || existing === "" ? "" : "\n") + toAdd.join("\n") + "\n";
  await fs.writeFile(gitignorePath, existing + addition, "utf-8");

  consola.success(`Updated .gitignore (added: ${toAdd.join(", ")}).`);
};
