import fs from "node:fs/promises";
import { webcrypto } from "node:crypto";
import { consola } from "consola";
import { functionsIndexTemplate } from "../templates/functions";
import { schemaTemplate } from "../templates/schema";
import { wranglerJsonTemplate } from "../templates/wrangler";
import type { WranglerOptions } from "../templates/wrangler";
import { genTypesTemplate } from "../templates/types";
import { serverTemplate } from "../templates/server";
import type { DataLocationOptions } from "../templates/server";

export const createFiles = async (projectRoot: string, opts?: DataLocationOptions) => {
  const emptyMigrationsIndex = `// Auto-generated by EdgePod CLI — do not edit manually.
// Run \`edgepod build\` to regenerate after schema changes.

export default null;
`;

  const files = [
    ["edgepod/types.ts", genTypesTemplate()],
    ["edgepod/schema.ts", schemaTemplate()],
    ["edgepod/functions/index.ts", functionsIndexTemplate()],
    ["edgepod/.generated/server.ts", serverTemplate(opts)],
    ["edgepod/.generated/migrations/index.ts", emptyMigrationsIndex],
  ];

  const results = await Promise.all(
    files.map(async (file) => {
      const fullPath = `${projectRoot}/${file[0]}`;
      await fs.mkdir(fullPath.substring(0, fullPath.lastIndexOf("/")), { recursive: true });
      return fs
        .writeFile(fullPath, file[1] ?? "", { flag: "wx" })
        .then(() => true)
        .catch((e: NodeJS.ErrnoException) => {
          if (e.code === "EEXIST") return false;
          throw e;
        });
    })
  );

  const created = results.filter(Boolean).length;

  if (created === files.length) {
    consola.success("Created project files.");
  } else if (created === 0) {
    consola.warn("Project files already exist, skipping.");
  } else {
    consola.success(`Created ${created} project file(s).`);
    consola.warn(`${files.length - created} file(s) already existed, skipped.`);
  }
};

export const generateWranglerFromTemplate = async (projectRoot: string, opts: WranglerOptions) => {
  const wranglerJsonPath = `${projectRoot}/edgepod/wrangler.json`;
  await fs.mkdir(`${projectRoot}/edgepod`, { recursive: true });

  const created = await fs
    .writeFile(wranglerJsonPath, wranglerJsonTemplate(opts), { flag: "wx" })
    .then(() => true)
    .catch((e: NodeJS.ErrnoException) => {
      if (e.code === "EEXIST") return false;
      throw e;
    });

  if (created) {
    consola.success("Created edgepod/wrangler.json.");
  } else {
    consola.warn("edgepod/wrangler.json already exists, skipping.");
  }
};

export const readEnvVar = async (projectRoot: string, key: string): Promise<string | null> => {
  const envPath = `${projectRoot}/edgepod/.env`;
  let content: string;
  try {
    content = await fs.readFile(envPath, "utf-8");
  } catch {
    return null;
  }
  const match = content.match(new RegExp(`^${key}=(.+)$`, "m"));
  return match?.[1]?.trim() ?? null;
};

export const writeEnvFile = async (projectRoot: string, vars: Record<string, string>) => {
  const envPath = `${projectRoot}/edgepod/.env`;
  const content =
    Object.entries(vars)
      .map(([k, v]) => `${k}=${v}`)
      .join("\n") + "\n";

  const created = await fs
    .writeFile(envPath, content, { flag: "wx" })
    .then(() => true)
    .catch((e: NodeJS.ErrnoException) => {
      if (e.code === "EEXIST") return false;
      throw e;
    });

  if (created) {
    consola.success("Created edgepod/.env with your API key.");
  } else {
    consola.warn("edgepod/.env already exists, skipping.");
  }
};

// Returns the private key JWK as a compact JSON string for storage in .env
export const writeJwksFiles = async (projectRoot: string): Promise<string> => {
  const { subtle } = webcrypto;
  const keyPair = await subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, [
    "sign",
    "verify",
  ]);

  const [privateJwk, publicJwk] = await Promise.all([
    subtle.exportKey("jwk", keyPair.privateKey),
    subtle.exportKey("jwk", keyPair.publicKey),
  ]);

  const jwks = { keys: [{ ...publicJwk, kid: "edgepod-local-key", use: "sig", alg: "ES256" }] };
  const wellKnownDir = `${projectRoot}/edgepod/.generated/public/.well-known`;

  await fs.mkdir(wellKnownDir, { recursive: true });
  await fs.writeFile(`${wellKnownDir}/jwks.json`, JSON.stringify(jwks, null, 2), "utf-8");

  consola.success("Generated local JWKS key pair.");
  return JSON.stringify(privateJwk);
};

export const updateGitignore = async (projectRoot: string) => {
  const gitignorePath = `${projectRoot}/.gitignore`;
  const entries = ["edgepod/.env", "edgepod/.wrangler", "!edgepod/"];

  let existing = "";
  try {
    existing = await fs.readFile(gitignorePath, "utf-8");
  } catch {
    // file doesn't exist yet — we'll create it
  }

  const lines = existing.split("\n").map((l) => l.trim());
  const toAdd = entries.filter((e) => !lines.includes(e));

  if (toAdd.length === 0) return;

  const addition =
    (existing.endsWith("\n") || existing === "" ? "" : "\n") + toAdd.join("\n") + "\n";
  await fs.writeFile(gitignorePath, existing + addition, "utf-8");

  consola.success(`Updated .gitignore (added: ${toAdd.join(", ")}).`);
};
