import fs from "node:fs/promises";
import path from "node:path";
import { generateSQLiteDrizzleJson, generateSQLiteMigration } from "drizzle-kit/api";
import type { DrizzleSQLiteSnapshotJSON } from "drizzle-kit/api";
import { consola } from "consola";

interface SnapshotColumn {
  type: string;
}

interface SnapshotTable {
  columns: Record<string, SnapshotColumn>;
}

interface SnapshotTables {
  tables: Record<string, SnapshotTable>;
}

const SNAPSHOT_FILE = "snapshot.json";
const JOURNAL_FILE = "meta/_journal.json";

interface JournalEntry {
  idx: number;
  tag: string;
  when: number;
  breakpoints: boolean;
}

interface Journal {
  entries: JournalEntry[];
}

const emptySnapshot = (): DrizzleSQLiteSnapshotJSON => ({
  version: "6",
  dialect: "sqlite",
  tables: {},
  views: {},
  enums: {},
  _meta: { tables: {}, columns: {} },
  id: "00000000-0000-0000-0000-000000000000",
  prevId: "00000000-0000-0000-0000-000000000000",
});

async function loadJson<T>(filePath: string, fallback: () => T): Promise<T> {
  try {
    return JSON.parse(await fs.readFile(filePath, "utf-8")) as T;
  } catch {
    return fallback();
  }
}

async function writeMigrationsIndex(
  outputDir: string,
  journal: Journal,
  sqlContents: Map<string, string>,
): Promise<void> {
  const migrationsObj = journal.entries
    .map((e) => {
      const key = `m${String(e.idx).padStart(4, "0")}`;
      const sql = sqlContents.get(e.tag) ?? "";
      return `  ${JSON.stringify(key)}: ${JSON.stringify(sql)},`;
    })
    .join("\n");

  const content = `// This file is auto-generated by EdgePod CLI. Do not edit manually.

export default {
  journal: ${JSON.stringify(journal, null, 2)},
  migrations: {
${migrationsObj}
  },
};
`;

  await fs.writeFile(path.join(outputDir, "index.ts"), content, "utf-8");
}

async function warnColumnTypeChanges(
  prev: DrizzleSQLiteSnapshotJSON,
  cur: DrizzleSQLiteSnapshotJSON,
): Promise<void> {
  const changes: { table: string; column: string; from: string; to: string }[] = [];
  const prevTables = (prev as unknown as SnapshotTables).tables;
  const curTables = (cur as unknown as SnapshotTables).tables;

  for (const [tableName, curTable] of Object.entries(curTables)) {
    const prevTable = prevTables[tableName];
    if (!prevTable) continue;

    for (const [colName, curCol] of Object.entries(curTable.columns)) {
      const prevCol = prevTable.columns[colName];
      if (prevCol && prevCol.type !== curCol.type) {
        changes.push({ table: tableName, column: colName, from: prevCol.type, to: curCol.type });
      }
    }
  }

  if (changes.length === 0) return;

  consola.warn("SQLite does not support changing column types directly.");
  consola.warn("The following columns will be dropped and recreated — existing data will be lost:");
  for (const c of changes) {
    consola.log(`  ${c.table}.${c.column}: ${c.from} → ${c.to}`);
  }

  const confirmed = await consola.prompt("Proceed and generate the migration anyway?", {
    type: "confirm",
    initial: false,
  });

  if (!confirmed) {
    consola.info("Migration aborted.");
    process.exit(0);
  }
}

export async function generateMigrationFiles(
  rootPath: string,
  schemaRelPath: string = "edgepod/schema.ts",
  outputRelDir: string = "edgepod/.generated/migrations",
): Promise<void> {
  const absSchemaPath = path.resolve(rootPath, schemaRelPath);
  const absOutputDir = path.resolve(rootPath, outputRelDir);

  const [prevSnapshot, journal] = await Promise.all([
    loadJson<DrizzleSQLiteSnapshotJSON>(path.join(absOutputDir, SNAPSHOT_FILE), emptySnapshot),
    loadJson<Journal>(path.join(absOutputDir, JOURNAL_FILE), () => ({ entries: [] })),
  ]);

  const userSchema = await import(absSchemaPath);
  const curSnapshot = await generateSQLiteDrizzleJson(userSchema, prevSnapshot.id);

  await warnColumnTypeChanges(prevSnapshot, curSnapshot);

  const statements = await generateSQLiteMigration(prevSnapshot, curSnapshot);

  if (statements.length > 0) {
    await fs.mkdir(path.join(absOutputDir, "meta"), { recursive: true });

    const idx = journal.entries.length;
    const tag = `${String(idx).padStart(4, "0")}_migration`;
    const sqlContent = statements.join("\n--> statement-breakpoint\n");

    await fs.writeFile(path.join(absOutputDir, `${tag}.sql`), sqlContent, "utf-8");

    journal.entries.push({ idx, tag, when: Date.now(), breakpoints: true });

    await Promise.all([
      fs.writeFile(
        path.join(absOutputDir, JOURNAL_FILE),
        JSON.stringify(journal, null, 2),
        "utf-8",
      ),
      fs.writeFile(
        path.join(absOutputDir, SNAPSHOT_FILE),
        JSON.stringify(curSnapshot, null, 2),
        "utf-8",
      ),
    ]);

    consola.success(`Migration ${tag} written.`);
  } else {
    consola.info("No schema changes detected.");
  }

  // Load all SQL files and inline them into the index (no wrangler text module rules needed)
  const sqlContents = new Map<string, string>();
  for (const entry of journal.entries) {
    const sql = await fs
      .readFile(path.join(absOutputDir, `${entry.tag}.sql`), "utf-8")
      .catch(() => "");
    sqlContents.set(entry.tag, sql);
  }

  await writeMigrationsIndex(absOutputDir, journal, sqlContents);
}
