import fs from "node:fs/promises";
import path from "node:path";
import { generateSQLiteDrizzleJson, generateSQLiteMigration } from "drizzle-kit/api";
import type { DrizzleSQLiteSnapshotJSON } from "drizzle-kit/api";
import { consola } from "consola";

const SNAPSHOT_FILE = "snapshot.json";
const JOURNAL_FILE = "meta/_journal.json";

interface JournalEntry {
  idx: number;
  tag: string;
  when: number;
  breakpoints: boolean;
}

interface Journal {
  entries: JournalEntry[];
}

const emptySnapshot = (): DrizzleSQLiteSnapshotJSON => ({
  version: "6",
  dialect: "sqlite",
  tables: {},
  views: {},
  enums: {},
  _meta: { tables: {}, columns: {} },
  id: "00000000-0000-0000-0000-000000000000",
  prevId: "00000000-0000-0000-0000-000000000000",
});

async function loadJson<T>(filePath: string, fallback: () => T): Promise<T> {
  try {
    return JSON.parse(await fs.readFile(filePath, "utf-8")) as T;
  } catch {
    return fallback();
  }
}

async function writeMigrationsIndex(outputDir: string, journal: Journal): Promise<void> {
  const imports = journal.entries
    .map((e) => `import m${String(e.idx).padStart(4, "0")} from "./${e.tag}.sql";`)
    .join("\n");

  const migrationsObj = journal.entries
    .map((e) => `    m${String(e.idx).padStart(4, "0")},`)
    .join("\n");

  const content = `// This file is auto-generated by EdgePod CLI. Do not edit manually.
${imports}

export default {
  journal: ${JSON.stringify(journal, null, 2)},
  migrations: {
${migrationsObj}
  },
};
`;

  await fs.writeFile(path.join(outputDir, "index.ts"), content, "utf-8");
}

export async function generateMigrationFiles(
  rootPath: string,
  schemaRelPath: string = "edgepod/schema.ts",
  outputRelDir: string = "edgepod/.generated/migrations"
): Promise<void> {
  const absSchemaPath = path.resolve(rootPath, schemaRelPath);
  const absOutputDir = path.resolve(rootPath, outputRelDir);

  const [prevSnapshot, journal] = await Promise.all([
    loadJson<DrizzleSQLiteSnapshotJSON>(path.join(absOutputDir, SNAPSHOT_FILE), emptySnapshot),
    loadJson<Journal>(path.join(absOutputDir, JOURNAL_FILE), () => ({ entries: [] })),
  ]);

  const userSchema = await import(absSchemaPath);
  const curSnapshot = await generateSQLiteDrizzleJson(userSchema, prevSnapshot.id);
  const statements = await generateSQLiteMigration(prevSnapshot, curSnapshot);

  if (statements.length === 0) {
    consola.warn("No schema changes detected, no migration generated.");
    return;
  }

  await fs.mkdir(path.join(absOutputDir, "meta"), { recursive: true });

  const idx = journal.entries.length;
  const tag = `${String(idx).padStart(4, "0")}_migration`;
  const sqlContent = statements.join("\n--> statement-breakpoint\n");

  await fs.writeFile(path.join(absOutputDir, `${tag}.sql`), sqlContent, "utf-8");

  journal.entries.push({ idx, tag, when: Date.now(), breakpoints: true });

  await Promise.all([
    fs.writeFile(path.join(absOutputDir, JOURNAL_FILE), JSON.stringify(journal, null, 2), "utf-8"),
    fs.writeFile(
      path.join(absOutputDir, SNAPSHOT_FILE),
      JSON.stringify(curSnapshot, null, 2),
      "utf-8"
    ),
  ]);

  await writeMigrationsIndex(absOutputDir, journal);
  consola.success(`Migration ${tag} written.`);
}
